//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public long UserID { get; set; }
        public string LoginName { get; set; }
        public string DispalyName { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DataCreated_Date { get; set; }
        public Nullable<long> DataCreated_By { get; set; }
        public Nullable<System.DateTime> DataChanged_Date { get; set; }
        public Nullable<long> DataChanged_By { get; set; }
    }
}
