//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperLog
    {
        public long LogID { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<byte> OperType { get; set; }
        public string EntityID { get; set; }
        public byte[] Content { get; set; }
        public Nullable<System.DateTime> DataCreated_Date { get; set; }
        public Nullable<long> DataCreated_By { get; set; }
        public Nullable<System.DateTime> DataChanged_Date { get; set; }
        public Nullable<long> DataChanged_By { get; set; }
    }
}
